In [10]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib.pyplot as plt


In [11]:
print(torch.__version__)

2.4.1+cu121


In [12]:
!nvidia-smi

Sat Oct 12 18:14:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [14]:
#intro to tensor

In [13]:
#creating Tensors
# pytorch tensor are created using torch.tensor

In [17]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [18]:
scalar.ndim

0

In [19]:
scalar.item()

7

In [21]:
vector=torch.tensor([3,4])

In [22]:
vector

tensor([3, 4])

In [23]:
matrix=torch.tensor([[1,2],[3,4]])

In [24]:
matrix

tensor([[1, 2],
        [3, 4]])

In [25]:
matrix.ndim

2

In [28]:
matrix.shape

torch.Size([2, 2])

In [29]:
 TENSOR=torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])

In [30]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [35]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [40]:
What=torch.tensor([[[[1,2,3]]]])

In [41]:
What.ndim

4

In [42]:
What.shape

torch.Size([1, 1, 1, 3])

In [44]:
What


tensor([[[[1, 2, 3]]]])

In [53]:
random_tensor=torch.rand(10,10,10)

In [54]:
random_tensor


tensor([[[0.7799, 0.1717, 0.6455, 0.1077, 0.7849, 0.6761, 0.2326, 0.7532,
          0.3186, 0.2615],
         [0.2016, 0.4174, 0.8556, 0.6672, 0.9483, 0.9408, 0.4999, 0.6314,
          0.0107, 0.2597],
         [0.1706, 0.3043, 0.9781, 0.0592, 0.0618, 0.8868, 0.6747, 0.9387,
          0.4513, 0.8665],
         [0.8849, 0.7045, 0.8555, 0.4616, 0.5943, 0.6626, 0.3876, 0.8854,
          0.2506, 0.7102],
         [0.1237, 0.5512, 0.6652, 0.2044, 0.5412, 0.5899, 0.1912, 0.3695,
          0.5235, 0.6888],
         [0.9376, 0.8081, 0.6070, 0.7792, 0.6508, 0.1421, 0.1950, 0.7097,
          0.0960, 0.4517],
         [0.8442, 0.6107, 0.1648, 0.0363, 0.1361, 0.4311, 0.5549, 0.0393,
          0.3139, 0.2066],
         [0.5257, 0.9089, 0.6008, 0.3127, 0.2451, 0.6569, 0.5586, 0.5109,
          0.4644, 0.1888],
         [0.0968, 0.1661, 0.2873, 0.3756, 0.5166, 0.3359, 0.2344, 0.4764,
          0.8686, 0.8470],
         [0.3728, 0.1716, 0.8796, 0.8255, 0.7659, 0.5514, 0.9283, 0.1859,
          0.5209,

In [55]:
random_tensor.ndim

3

In [56]:
random_tensor.shape

torch.Size([10, 10, 10])

In [57]:
#create a randm tensor with image size

In [61]:
random_image_tensor=torch.rand(size=(3,24,224)) # height width color channel

In [63]:
random_image_tensor.size() ,random_image_tensor.ndim

(torch.Size([3, 24, 224]), 3)