In [10]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib.pyplot as plt


In [11]:
print(torch.__version__)

2.4.1+cu121


In [12]:
!nvidia-smi

Sat Oct 12 18:14:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [14]:
#intro to tensor

In [13]:
#creating Tensors
# pytorch tensor are created using torch.tensor

In [17]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [18]:
scalar.ndim

0

In [19]:
scalar.item()

7

In [21]:
vector=torch.tensor([3,4])

In [22]:
vector

tensor([3, 4])

In [23]:
matrix=torch.tensor([[1,2],[3,4]])

In [24]:
matrix

tensor([[1, 2],
        [3, 4]])

In [25]:
matrix.ndim

2

In [28]:
matrix.shape

torch.Size([2, 2])

In [29]:
 TENSOR=torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])

In [30]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])